export const GA4_STANDARD_EVENTS = [
  // E-commerce
  { name: 'view_item_list', category: 'E-commerce' },
  { name: 'select_item', category: 'E-commerce' },
  { name: 'view_item', category: 'E-commerce' },
  { name: 'add_to_cart', category: 'E-commerce' },
  { name: 'remove_from_cart', category: 'E-commerce' },
  { name: 'view_cart', category: 'E-commerce' },
  { name: 'begin_checkout', category: 'E-commerce' },
  { name: 'add_shipping_info', category: 'E-commerce' },
  { name: 'add_payment_info', category: 'E-commerce' },
  { name: 'purchase', category: 'E-commerce' },
  { name: 'refund', category: 'E-commerce' },
  { name: 'add_to_wishlist', category: 'E-commerce' },
  // Engagement
  { name: 'page_view', category: 'Engagement' },
  { name: 'scroll', category: 'Engagement' },
  { name: 'click', category: 'Engagement' },
  { name: 'view_search_results', category: 'Engagement' },
  { name: 'search', category: 'Engagement' },
  { name: 'share', category: 'Engagement' },
  { name: 'file_download', category: 'Engagement' },
  { name: 'video_start', category: 'Engagement' },
  { name: 'video_progress', category: 'Engagement' },
  { name: 'video_complete', category: 'Engagement' },
  { name: 'form_start', category: 'Engagement' },
  { name: 'form_submit', category: 'Engagement' },
  // Auth
  { name: 'login', category: 'Auth' },
  { name: 'sign_up', category: 'Auth' },
  // Ads
  { name: 'generate_lead', category: 'Ads' },
  { name: 'earn_virtual_currency', category: 'Ads' },
  { name: 'spend_virtual_currency', category: 'Ads' },
]

export const GA4_STANDARD_PARAMETERS = [
  { name: 'item_id', type: 'string' },
  { name: 'item_name', type: 'string' },
  { name: 'item_category', type: 'string' },
  { name: 'item_brand', type: 'string' },
  { name: 'item_variant', type: 'string' },
  { name: 'price', type: 'number' },
  { name: 'quantity', type: 'number' },
  { name: 'currency', type: 'string' },
  { name: 'value', type: 'number' },
  { name: 'transaction_id', type: 'string' },
  { name: 'affiliation', type: 'string' },
  { name: 'coupon', type: 'string' },
  { name: 'discount', type: 'number' },
  { name: 'shipping', type: 'number' },
  { name: 'tax', type: 'number' },
  { name: 'payment_type', type: 'string' },
  { name: 'shipping_tier', type: 'string' },
  { name: 'user_id', type: 'string' },
  { name: 'session_id', type: 'string' },
  { name: 'page_title', type: 'string' },
  { name: 'page_location', type: 'string' },
  { name: 'search_term', type: 'string' },
  { name: 'content_type', type: 'string' },
  { name: 'content_id', type: 'string' },
]
